package org.libsdl.app;

public interface SDLConstants  {

    // Cursor types
    // private static final int SDL_SYSTEM_CURSOR_NONE = -1;
     int SDL_SYSTEM_CURSOR_ARROW = 0;
     int SDL_SYSTEM_CURSOR_IBEAM = 1;
     int SDL_SYSTEM_CURSOR_WAIT = 2;
     int SDL_SYSTEM_CURSOR_CROSSHAIR = 3;
     int SDL_SYSTEM_CURSOR_WAITARROW = 4;
     int SDL_SYSTEM_CURSOR_SIZENWSE = 5;
     int SDL_SYSTEM_CURSOR_SIZENESW = 6;
     int SDL_SYSTEM_CURSOR_SIZEWE = 7;
     int SDL_SYSTEM_CURSOR_SIZENS = 8;
     int SDL_SYSTEM_CURSOR_SIZEALL = 9;
     int SDL_SYSTEM_CURSOR_NO = 10;
     int SDL_SYSTEM_CURSOR_HAND = 11;
     int SDL_SYSTEM_CURSOR_WINDOW_TOPLEFT = 12;
     int SDL_SYSTEM_CURSOR_WINDOW_TOP = 13;
     int SDL_SYSTEM_CURSOR_WINDOW_TOPRIGHT = 14;
     int SDL_SYSTEM_CURSOR_WINDOW_RIGHT = 15;
     int SDL_SYSTEM_CURSOR_WINDOW_BOTTOMRIGHT = 16;
     int SDL_SYSTEM_CURSOR_WINDOW_BOTTOM = 17;
     int SDL_SYSTEM_CURSOR_WINDOW_BOTTOMLEFT = 18;
     int SDL_SYSTEM_CURSOR_WINDOW_LEFT = 19;
     int SDL_ORIENTATION_UNKNOWN = 0;
     int SDL_ORIENTATION_LANDSCAPE = 1;
     int SDL_ORIENTATION_LANDSCAPE_FLIPPED = 2;
     int SDL_ORIENTATION_PORTRAIT = 3;
     int SDL_ORIENTATION_PORTRAIT_FLIPPED = 4;
}
